### ISSUE TITLE
Update failures

### ISSUE THREAD

**Issue by ysndr** [flox/not-nixpkgs#1]
### Steps To Reproduce
1. build *X*

### Build log
```
log here if short otherwise a link to a gist
```

### Metadata
Please run `nix-shell -p nix-info --run "nix-info -m"` and paste the result.

```console
[user@system:~]$ nix-shell -p nix-info --run "nix-info -m"
output here
```

**Comment by limeytexan** [comment]
This issue appears to be a log of failures .. @ysndr I'll close this out. Let me know if we need a category for _open_ issues used as logs. (If we can instead log to closed issues, or issues that can be closed and automatically reopened with log input then that's fine.)
